### ISSUE TITLE
Ouvrir un issue pour le cours FAS1002

### ISSUE THREAD

**Issue by stephanielapierre** [stephanielapierre/github-slideshow#4]
Bonjour @SamGuay

Voici mon nouvel issue pour le quizz #6.

Réaction quand tu réussi à répondre à une question complexe des quizz :-)

![giphy](https://user-images.githubusercontent.com/90524644/136820492-07646786-d3d9-4d01-8ecc-b4c9e6919e3e.gif)

Merci!

**Comment by SamGuay** [comment]
Génial! J'adore ton GIF! 

Je confirme que tout me semble beau, ta présentation apparait au https://stephanielapierre.github.io/github-slideshow et tout semble fonctionnel! 

À demain
